# Generated by Django 3.0.7 on 2020-08-11 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('external_appearance', models.ImageField(blank=True, null=True, upload_to='hotels')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('website', models.URLField(blank=True, null=True, unique=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hotels')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('single_bed', models.PositiveSmallIntegerField(default=0)),
                ('double_bed', models.PositiveSmallIntegerField(default=0)),
                ('size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_fee', models.PositiveSmallIntegerField(default=0, null=True)),
                ('usage_fee', models.PositiveSmallIntegerField(default=0, null=True)),
                ('utility_bill', models.PositiveSmallIntegerField(default=0, null=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
