# Generated by Django 3.0.7 on 2020-08-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(max_length=155)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rank.Service')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rank.Service'),
        ),
    ]
