# Generated by Django 3.0.7 on 2020-09-24 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200816_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(max_length=155)),
            ],
        ),
        migrations.RemoveField(
            model_name='rank',
            name='service',
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='MilitaryBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(max_length=155)),
                ('military_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rank.MilitaryService')),
            ],
        ),
        migrations.AddField(
            model_name='rank',
            name='military_service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='rank.MilitaryService'),
        ),
    ]
