# Generated by Django 3.0.7 on 2020-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20200924_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='equivalent_NATO_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='militarybranch',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
