# Generated by Django 3.0.7 on 2020-09-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0004_auto_20200925_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['equivalent_NATO_code']},
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='slug',
            field=models.SlugField(max_length=155, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=155, unique=True),
        ),
    ]
