# Generated by Django 3.0.7 on 2020-08-20 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0002_auto_20200814_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_applicant', models.CharField(max_length=50)),
                ('use', models.PositiveSmallIntegerField(default=1)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('booked_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.CharField(blank=True, max_length=155, null=True)),
                ('relationship', models.CharField(blank=True, max_length=155, null=True)),
                ('ID_Number', models.CharField(max_length=15)),
                ('gender', models.CharField(default='男', max_length=4)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('licence_plate', models.CharField(max_length=10, null=True)),
                ('booking_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booking')),
            ],
        ),
    ]
