# Generated by Django 3.0.7 on 2020-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='licence_plate',
            new_name='license_plate',
        ),
    ]
