# Generated by Django 3.1.2 on 2020-11-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200827_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='origin_info_txt',
            field=models.TextField(null=True),
        ),
    ]
