# Generated by Django 3.0.7 on 2020-08-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200814_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_superuser',)},
        ),
    ]
