# Generated by Django 3.0.7 on 2020-09-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200820_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_Number',
            new_name='phone_number',
        ),
    ]
