# Generated by Django 3.0.7 on 2020-09-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200902_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='serve_record',
            field=models.TextField(blank=True, null=True),
        ),
    ]
