# Generated by Django 3.0.7 on 2020-09-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200816_1147'),
        ('registration', '0006_officer_serve_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.Rank'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='service_state',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
