# Generated by Django 3.0.7 on 2020-09-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_auto_20200816_1147'),
        ('registration', '0007_auto_20200922_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='service_state',
        ),
        migrations.AddField(
            model_name='officer',
            name='attachment_of_badge_back',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='officer',
            name='attachment_of_badge_front',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='officer',
            name='attachment_of_military_ID_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='officer',
            name='attachment_of_military_ID_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='officer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.Branch'),
        ),
        migrations.AddField(
            model_name='officer',
            name='date_of_enlist',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='date_of_retire',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='military_service',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='serve_state',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.Service'),
        ),
    ]
