# Generated by Django 3.0.7 on 2020-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20200922_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='identity_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
