# Generated by Django 3.0.7 on 2020-09-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_auto_20200924_0912'),
        ('registration', '0009_officer_identity_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='military_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.MilitaryBranch'),
        ),
        migrations.AddField(
            model_name='officer',
            name='military_service_state',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='military_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rank.MilitaryService'),
        ),
    ]
