# Generated by Django 3.0.7 on 2020-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_education_experience_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('finished_date',)},
        ),
        migrations.AlterField(
            model_name='experience',
            name='finished_date',
            field=models.DateField(null=True),
        ),
    ]
