# Generated by Django 3.0.7 on 2020-10-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20200929_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('finished_date',)},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('started_date',)},
        ),
    ]
