# Generated by Django 3.0.7 on 2020-09-28 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proclamation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proclamation',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
